cv:
  layout:
    font: Arial
    title-font-size: 15
    header-font-size: 14
    details-font-size: 11
    image-size: 40
    first-color: "#001F3F"
    second-color: "#CCCCCC"
    width-bar: 60
    height-bar: 297
  personal-info:
    - name: Wijnand van der Meijs
    - name: +03161111118
      icon-path: phone_icon.png
      icon-size: 8
      icon-x-coordinate: 25
    - name: wijnand@gmail.com
      icon-path: mail_icon.png
      icon-size: 8
      icon-x-coordinate: 25
  languages:
    - name: Dutch
      proficiency: '****'
    - name: English
      proficiency: '****'
    - name: German
      proficiency: '***'
    - name: Spanish
      proficiency: '**'
  profile:
    - time-frame: ""
      details: ""
      content: "Big description \nof something \nalso something like this \nand this and even \nthis"
  education:
    - time-frame: 2006-2013
      details: 
        title: High School
    - time-frame: 2014-2017
      details:
        title: Bachelor on an interesting subject, University of a Place
    - time-frame: 2017-2019
      details:
        title: Master on an interesting subject, University of a Place
  experience:
    - time-frame: 2019-2020
      details:
        title: Interesting Job
        company: Company Name
        description:
            - Created some stuff
            - Created some more stuff
    - time-frame: 2021-Now
      details:
        title: Interesting Job number 2
        company: Company Name 2
        description:
            - Did some stuff
            - Did some more stuff
            - Did even more stuff
  certifications:
    - time-frame: november 2021
      details: 
        title: Certified Kubernetes Application Developer
        link: www.google.com
    - time-frame: january 2021
      details:
        title: Microsoft Azure Data Engineer DP203
        link: www.youtube.com
    - time-frame: december 2022
      details:
        title: Microsoft Azure Data Engineer AZ204
        link: "https://scholar.google.com/"