cv:
  layout:
    font: Arial
    title-font-size: 15
    header-font-size: 14
    details-font-size: 11
    image-size: 40
    first-color: "#001F3F"
    second-color: "#CCCCCC"
    width-bar: 60
    height-bar: 297
  online-presence:
    - icon-path: linkedin_icon.png
      icon-size: 8
      icon-x-coordinate: 20
      link: www.google.com
    - icon-path: github_icon.png
      icon-size: 8
      icon-x-coordinate: 30
      link: www.google.com
  personal-info:
    - item: Wijnand van der Meijs
    - item: +03161111118
      icon-path: phone_icon.png
      icon-size: 8
      icon-x-coordinate: 25
    - item: wijnand@gmail.com
      icon-path: mail_icon.png
      icon-size: 8
      icon-x-coordinate: 25
  languages:
    - language: Dutch
      proficiency: '****'
    - language: English
      proficiency: '****'
    - language: German
      proficiency: '***'
    - language: Spanish
      proficiency: '**'
  sections:
    profile:
      title: Profile
      section-content:
        - time-frame: ""
          details: ""
          content: "Big description \nof something \nalso something like this \nand this and even \nthis"
    experience:
      title: Work History
      section-content:
        - time-frame: 2019-2020
          details:
            title: Interesting Job
            description:
                - Created some stuff
                - Created some more stuff
        - time-frame: 2021-Now
          details:
            title: Interesting Job number 2
            description:
                - Did some stuff
                - Did some more stuff
                - Did even more stuff
    projects:
      title: Projects
      section-content:
        - time-frame: 2022-2023
          details:
            title: Awesome Project 01
            image-path: images/project_01.png
            link: ""
    certifications:
      title: Certifications
      section-content:
        - time-frame: november 2021
          details: 
            title: Certified Kubernetes Application Developer
            link: www.google.com
        - time-frame: january 2021
          details:
            title: Microsoft Azure Data Engineer DP203
            link: www.youtube.com
        - time-frame: december 2022
          details:
            title: Microsoft Azure Data Engineer AZ204
            link: "https://scholar.google.com/"
    education:
      title: Education
      section-content:
        - time-frame: 2006-2013
          details: 
            title: High School
        - time-frame: 2014-2017
          details:
            title: Bachelor on an interesting subject, University of a Place
        - time-frame: 2017-2019
          details:
            title: Master on an interesting subject, University of a Place