cv:
  layout:
    font: Arial
    header-font-size: 14
    details-font-size: 11
    first-color:
      red: 50
      green: 50
      blue: 100
    second-color:
      red: 180
      green: 180
      blue: 200
    width-bar: 65
    height-bar: 297
  personal-info:
    name: Wijnand van der Meijs
    address: AnAddress
    phone-number: +03161111118
    email-address: w@gmail.com
  languages:
    - name: Dutch
      proficiency: '****'
    - name: English
      proficiency: '****'
    - name: German
      proficiency: '***'
    - name: Spanish
      proficiency: '**'
  education:
    - time-frame: 2006-2013
      details: High School
    - time-frame: 2014-2017
      details: Bachelor on an interesting subject, University of a Place # add year
    - time-frame: 2017-2019
      details: Master on an interesting subject, University of a Place # add year
  experience:
    - time-frame: 2019-2020
      details:
        title: Interesting Job
        company: Company Name
        description:
            - Created some stuff
            - Created some more stuff
    - time-frame: 2021-Now
      details:
        title: Interesting Job number 2
        company: Company Name 2
        description:
            - Did some stuff
            - Did some more stuff
            - Did even more stuff
